version: 2.1

orbs:
  windows: circleci/windows@2.4.1

jobs:
  build-and-test-windows-dev:
    executor:
      name: windows/default
      shell: powershell.exe

    steps:
      - checkout
      # upgrade
      - run:
          command: pip install --upgrade --user pip setuptools wheel
          name: pip install --upgrade --user pip setuptools wheel
      # pip require package
      - run:
          command: pip install --user -r dev_requirements.txt
          name: pip dev_requirements.txt
      - run:
          command: |
                  $workdir = "c:\installer\" &&
                  If (Test-Path -Path $workdir -PathType Container) &&
                  { Write-Host "$workdir already exists" -ForegroundColor Red} &&
                  ELSE &&
                  { New-Item -Path $workdir  -ItemType directory } &&
                  $source = "https://download.mozilla.org/?product=firefox-latest&os=win64&lang=en-US" &&
                  $destination = "$workdir\firefox.exe" &&
                  if (Get-Command 'Invoke-Webrequest') &&
                  { Invoke-WebRequest $source -OutFile $destination } &&
                  else &&
                  { $WebClient = New-Object System.Net.WebClient &&
                  $webclient.DownloadFile($source, $destination) } &&
                  Start-Process -FilePath "$workdir\firefox.exe" -ArgumentList "/S" &&
                  Start-Sleep -s 35 &&
                  rm -Force $workdir/firefox*
          name: install firefox
      # desired_capabilities test
      - run:
          command: python ./test/desired_capabilities_test/desired_capabilities_test.py
          name: desired_capabilities_test
      # find_and_click test
      - run:
          command: python ./test/find_and_click_test/find_and_click_test.py
          name: find_and_click_test
      # multi_driver test
      - run:
          command: python ./test/multi_driver_test/multi_driver_test.py
          name: multi_driver test
      # start_webdriver_and_asset_title test
      - run:
          command: python ./test/start_webdriver_and_asset_title_test/title_test.py
          name: start_webdriver_and_asset_title test
      # get_webdriver test
      - run:
          command: python ./test/start_webdriver_test/get_webdriver.py
          name: get_webdriver
      # start_webdriver_with_options test
      - run:
          command: python ./test/start_webdriver_with_options/start_webdriver_with_options.py
          name: start_webdriver_with_options
      # test_object test
      - run:
          command: python ./test/test_object_test/test_object_test.py
          name: test_object_test
      # test
      - run:
          command: python ./test/test.py
          name: test

workflows:
  main:
    jobs:
      - build-and-test-windows-dev
