name: WebRunner Stable Python3.11

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build_stable_version:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install -r requirements.txt
    - name: Install firefox
      run: |
            $SourceURL = "https://download.mozilla.org/?product=firefox-latest&os=win&lang=en-US";
            $Installer = $env:TEMP + "\firefox.exe";
            Invoke-WebRequest $SourceURL -OutFile $Installer;
            Start-Process -FilePath $Installer -Args "/s" -Verb RunAs -Wait;
            Remove-Item $Installer;
    - name: Test Desired Capabilities
      run: python ./test/unit_test/desired_capabilities_test/desired_capabilities_test.py
    - name: Test Find And Click
      run: python ./test/unit_test/find_and_click_test/find_and_click_test.py
    - name: Test Multi Webdriver
      run: python ./test/unit_test/multi_driver_test/multi_driver_test.py
    - name: Test Start Webdriver And Assert Title
      run: python ./test/unit_test/start_webdriver_and_asset_title_test/title_test.py
    - name: Test Get Webdriver
      run: python ./test/unit_test/start_webdriver_test/get_webdriver.py
    - name: Test Start Webdriver With Options
      run: python ./test/unit_test/start_webdriver_with_options/webdriver_with_options.py
    - name: Test test_object
      run: python ./test/unit_test/test_object_test/test_object_test.py
    - name: Test Record Class
      run: python ./test/unit_test/test_record_class_test/test_record_class_test.py
    - name: Test Check Value
      run: python ./test/unit_test/check_value_test/check_value_test.py
    - name: Test Switch
      run: python ./test/unit_test/switch_test/switch_test.py
    - name: Test Close Choose Webdriver
      run: python ./test/unit_test/close_choose_webdriver_test/close_choose_webdriver_test.py
    - name: Test Redirect
      run: python ./test/unit_test/redirect_test/redirect_test.py
    - name: Test Cookie
      run: python ./test/unit_test/cookie_test/cookie_test.py
    - name: Test Set Timeout
      run: python ./test/unit_test/set_timeout_test/set_timeout_test.py
    - name: Test Action Chain
      run: python ./test/unit_test/action_chains_test/action_chains_test.py
    - name: Test Window
      run: python ./test/unit_test/window_test/window_test.py
    - name: Test Screenshot
      run: python ./test/unit_test/screenshot_test/screenshot_test.py
    - name: Test Executor
      run: python ./test/unit_test/executor_test/executor_test.py
    - name: Test Argparse
      run: python ./test/unit_test/argparse/argparse_test.py
    - name: Test Generate HTML Report
      run: python ./test/unit_test/report_test/html_report_test.py
    - name: Test Generate JSON Report
      run: python ./test/unit_test/report_test/json_report_test.py
    - name: Test Generate XML Report
      run: python ./test/unit_test/report_test/xml_report_test.py
    - name: Test Callback
      run: python ./test/unit_test/callback/callback_test.py
    - name: Test Interval Scheduler
      run: python ./test/unit_test/scheduler_test/sec_interval_test.py
    - name: Test Cron Scheduler
      run: python ./test/unit_test/scheduler_test/sec_cron_test.py